# -*- coding: utf-8 -*-
# Deployment settings for HelloWorld.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['C:/Marmalade/7.4/s3e/makefile_builder/mkb.py', 'e:/Documents/Michiel/Programmeren/Marmalade/HelloWorld/HelloWorld.mkb', '--buildenv=VC12X', '--test-assets', 'Default', '--fake-vc-call', '--deploy-only']
mkb = 'e:/Documents/Michiel/Programmeren/Marmalade/HelloWorld/HelloWorld.mkb'
mkf = []

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('e:/Documents/Michiel/Programmeren/Marmalade/HelloWorld\data', '.', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'HelloWorld'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'HelloWorld'
    long_caption = 'HelloWorld'
    version = [0, 0, 1]
    config = ['e:/Documents/Michiel/Programmeren/Marmalade/HelloWorld/data/app.icf']
    data_dir = 'e:/Documents/Michiel/Programmeren/Marmalade/HelloWorld/data'
    iphone_link_lib = []
    osx_ext_dll = []
    wp81_extra_pri = []
    ws8_ext_capabilities = []
    android_external_res = []
    win32_ext_dll = []
    wp8_ext_capabilities = []
    ws81_ext_managed_dll = []
    iphone_link_libdir = []
    wp81_ext_capabilities = []
    android_extra_application_manifest = []
    ws8_ext_native_dll = []
    android_external_assets = []
    blackberry_extra_descriptor = []
    ws8_extra_res = []
    android_extra_manifest = []
    wp81_ext_sdk_ref = []
    iphone_link_libdirs = []
    wp81_ext_device_capabilities = []
    linux_ext_lib = []
    ws8_ext_managed_dll = []
    ws8_ext_sdk_manifest_part = []
    ws8_ext_device_capabilities = []
    ws81_extra_pri = []
    android_external_jars = []
    win8_winrt_extra_res = []
    wp81_ext_sdk_manifest_part = []
    android_supports_gl_texture = []
    wp81_extra_res = []
    wp81_ext_managed_dll = []
    ws81_ext_sdk_manifest_part = []
    ws81_ext_device_capabilities = []
    ws8_ext_sdk_ref = []
    iphone_extra_string = []
    tizen_so = []
    wp8_ext_native_dll = []
    win8_phone_extra_res = []
    win8_store_extra_res = []
    iphone_link_opts = []
    ws81_ext_sdk_ref = []
    wp8_extra_res = []
    ws81_ext_native_dll = []
    ws8_extra_pri = []
    wp8_ext_managed_dll = []
    android_so = []
    wp8_ext_sdk_ref = []
    osx_extra_res = []
    ws81_extra_res = []
    wp81_ext_native_dll = []
    ws81_ext_capabilities = []
    iphone_link_libs = []
    target = {
         'gcc_x86' : {
                   'debug'   : r'e:/Documents/Michiel/Programmeren/Marmalade/HelloWorld/build_helloworld_vc12x/Debug_HelloWorld_VC12X_gcc_x86/HelloWorld.so',
                   'release' : r'e:/Documents/Michiel/Programmeren/Marmalade/HelloWorld/build_helloworld_vc12x/Release_HelloWorld_VC12X_gcc_x86/HelloWorld.so',
                 },
         'gcc_x86_tizen' : {
                   'debug'   : r'e:/Documents/Michiel/Programmeren/Marmalade/HelloWorld/build_helloworld_vc12x/Debug_HelloWorld_VC12X_gcc_x86_tizen/HelloWorld.s86',
                   'release' : r'e:/Documents/Michiel/Programmeren/Marmalade/HelloWorld/build_helloworld_vc12x/Release_HelloWorld_VC12X_gcc_x86_tizen/HelloWorld.s86',
                 },
         'firefoxos' : {
                   'debug'   : r'e:/Documents/Michiel/Programmeren/Marmalade/HelloWorld/build_helloworld_vc12x/Debug_HelloWorld_VC12X_firefoxos/HelloWorld.js',
                   'release' : r'e:/Documents/Michiel/Programmeren/Marmalade/HelloWorld/build_helloworld_vc12x/Release_HelloWorld_VC12X_firefoxos/HelloWorld.js',
                 },
         'mips_gcc' : {
                   'debug'   : r'e:/Documents/Michiel/Programmeren/Marmalade/HelloWorld/build_helloworld_vc12x/Debug_HelloWorld_VC12X_gcc_mips/HelloWorld.so',
                   'release' : r'e:/Documents/Michiel/Programmeren/Marmalade/HelloWorld/build_helloworld_vc12x/Release_HelloWorld_VC12X_gcc_mips/HelloWorld.so',
                 },
         'arm_gcc' : {
                   'debug'   : r'e:/Documents/Michiel/Programmeren/Marmalade/HelloWorld/build_helloworld_vc12x/Debug_HelloWorld_VC12X_gcc_arm/HelloWorld.s3e',
                   'release' : r'e:/Documents/Michiel/Programmeren/Marmalade/HelloWorld/build_helloworld_vc12x/Release_HelloWorld_VC12X_gcc_arm/HelloWorld.s3e',
                 },
         'mips' : {
                   'debug'   : r'e:/Documents/Michiel/Programmeren/Marmalade/HelloWorld/build_helloworld_vc12x/Debug_HelloWorld_VC12X_gcc_mips/HelloWorld.so',
                   'release' : r'e:/Documents/Michiel/Programmeren/Marmalade/HelloWorld/build_helloworld_vc12x/Release_HelloWorld_VC12X_gcc_mips/HelloWorld.so',
                 },
         'gcc_x86_android' : {
                   'debug'   : r'e:/Documents/Michiel/Programmeren/Marmalade/HelloWorld/build_helloworld_vc12x/Debug_HelloWorld_VC12X_gcc_x86_android/HelloWorld.so',
                   'release' : r'e:/Documents/Michiel/Programmeren/Marmalade/HelloWorld/build_helloworld_vc12x/Release_HelloWorld_VC12X_gcc_x86_android/HelloWorld.so',
                 },
         'arm' : {
                   'debug'   : r'e:/Documents/Michiel/Programmeren/Marmalade/HelloWorld/build_helloworld_vc12x/Debug_HelloWorld_VC12X_arm/HelloWorld.s3e',
                   'release' : r'e:/Documents/Michiel/Programmeren/Marmalade/HelloWorld/build_helloworld_vc12x/Release_HelloWorld_VC12X_arm/HelloWorld.s3e',
                 },
         'x86' : {
                   'debug'   : r'e:/Documents/Michiel/Programmeren/Marmalade/HelloWorld/build_helloworld_vc12x/Debug_HelloWorld_VC12X_x86/HelloWorld.s86',
                   'release' : r'e:/Documents/Michiel/Programmeren/Marmalade/HelloWorld/build_helloworld_vc12x/Release_HelloWorld_VC12X_x86/HelloWorld.s86',
                 },
        }
    arm_arch = ''
    assets_original = assets
    assets = assets['Default']

default = DefaultConfig()
